// <auto-generated />
using System;
using AireBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AireBooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250327012515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AireBooking.Models.Aire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VilleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VilleId");

                    b.ToTable("Aires");
                });

            modelBuilder.Entity("AireBooking.Models.Passager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passagers");
                });

            modelBuilder.Entity("AireBooking.Models.Reservation", b =>
                {
                    b.Property<int>("AireId")
                        .HasColumnType("int");

                    b.Property<int>("PassagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateArrivee")
                        .HasColumnType("datetime2");

                    b.Property<int>("HeureEstimee")
                        .HasColumnType("int");

                    b.HasKey("AireId", "PassagerId", "DateArrivee");

                    b.HasIndex("PassagerId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AireBooking.Models.Ville", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Villes");
                });

            modelBuilder.Entity("AireBooking.Models.Voiture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassagerId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PassagerId")
                        .IsUnique();

                    b.ToTable("Voitures");
                });

            modelBuilder.Entity("AireBooking.Models.Aire", b =>
                {
                    b.HasOne("AireBooking.Models.Ville", "Ville")
                        .WithMany("Aires")
                        .HasForeignKey("VilleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ville");
                });

            modelBuilder.Entity("AireBooking.Models.Reservation", b =>
                {
                    b.HasOne("AireBooking.Models.Aire", "Aire")
                        .WithMany("Reservations")
                        .HasForeignKey("AireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AireBooking.Models.Passager", "Passager")
                        .WithMany("Reservations")
                        .HasForeignKey("PassagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aire");

                    b.Navigation("Passager");
                });

            modelBuilder.Entity("AireBooking.Models.Voiture", b =>
                {
                    b.HasOne("AireBooking.Models.Passager", "Passager")
                        .WithOne("Voiture")
                        .HasForeignKey("AireBooking.Models.Voiture", "PassagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passager");
                });

            modelBuilder.Entity("AireBooking.Models.Aire", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AireBooking.Models.Passager", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Voiture")
                        .IsRequired();
                });

            modelBuilder.Entity("AireBooking.Models.Ville", b =>
                {
                    b.Navigation("Aires");
                });
#pragma warning restore 612, 618
        }
    }
}
